### ISSUE TITLE
*Please*... Add a max CPU option!

### ISSUE THREAD

**Issue by LEGOlord208** [nstafie/dca-rs#6]
I love the tool, used it many times. But using it on a huge file causes the computer to freeze. It's annoying...

Thanks!

**Comment by nstafie** [comment]
Hey, sorry for the late response. The next version I'm working on to be released in the near future has a --threads option to specify how many threads you want it to use, that should help with your problem.

**Comment by LEGOlord208** [comment]
Oo, thanks!
